name: Test Formula

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Test formula syntax
        run: |
          brew audit --strict --online Formula/pomo-tui.rb

      - name: Test installation (if release exists)
        continue-on-error: true
        run: |
          brew install ./Formula/pomo-tui.rb
          pomo-tui --version
          brew uninstall pomo-tui