# Default Configuration for pomo-tui
# ADHD-focused Pomodoro terminal application
#
# This file contains the default configuration settings.
# Copy to your config directory and modify as needed:
#   Linux: ~/.config/pomo-tui/config.toml
#   macOS: ~/Library/Application Support/pomo-tui/config.toml
#   Windows: %APPDATA%\pomo-tui\config.toml

[session]
# Session timing (minutes)
duration = 25                      # Default session length (15-50)
short_break_duration = 5           # Short break length (3-15)
long_break_duration = 15           # Long break length (10-30)
sessions_until_long_break = 4      # Sessions before long break (2-6)

# Automation settings
auto_start_breaks = true           # Automatically start breaks
auto_start_sessions = false        # Require manual session start
allow_break_skip = true            # Allow skipping breaks
session_end_sound = true           # Play sound when session ends

# ADHD-friendly features
gentle_transitions = true          # Gradual timer transitions
recovery_prompts = true            # Offer to resume interrupted sessions
focus_reminders = false            # Periodic gentle focus reminders (every 10min)

[audio]
# General audio settings
sound_enabled = true               # Enable all audio features
volume = 0.7                       # Master volume (0.0-1.0)

# Ambient sounds during sessions
ambient_enabled = true             # Play ambient sounds
ambient_sound = "brown_noise"      # Default ambient sound
ambient_volume = 0.5               # Relative to master volume
fade_in_duration = 3               # Seconds to fade in
fade_out_duration = 2              # Seconds to fade out

# Available ambient sounds:
# - brown_noise    (deep, rumbling - best for ADHD)
# - white_noise    (full spectrum static)
# - pink_noise     (balanced frequency)
# - rain           (light rain sounds)
# - forest         (nature with birds)
# - ocean          (ocean waves)
# - coffee_shop    (café ambiance)
# - library        (quiet atmosphere)
# - none           (no ambient sound)

# Notification sounds
notification_enabled = true        # Enable notification sounds
notification_sound = "soft_bell"   # Default notification sound
notification_volume = 0.8          # Relative to master volume

# When to play notifications
session_start_sound = true         # Sound when session starts
session_end_sound = true           # Sound when session completes
break_start_sound = false          # Sound when break starts
break_end_sound = true             # Sound when break ends

# Available notification sounds:
# - bell           (classic bell)
# - chime          (soft chime)
# - soft_bell      (gentle bell - recommended for ADHD)
# - ding           (simple notification)
# - completion     (achievement sound)
# - gentle         (very soft notification)
# - none           (no notification sound)

[ui]
# Visual theme
theme = "dark"                     # Theme: dark, light, auto

# Timer display
show_seconds = true                # Show seconds in timer
ascii_art_timer = true             # Use large ASCII art timer
progress_bar_style = "blocks"      # blocks, smooth, minimal

# Information display
show_session_count = true          # Show current session number
show_daily_goal = true             # Show daily progress indicator
show_productivity_score = true     # Show productivity score
show_time_of_day = false           # Show current time

# Layout options
compact_mode = false               # Use compact layout for small terminals
split_view = true                  # Split timer and task list
tab_navigation = true              # Enable tab-based navigation

# Daily goal settings
daily_session_goal = 8             # Target sessions per day
weekly_session_goal = 40           # Target sessions per week
goal_reminder = true               # Remind about daily goals

# ADHD-specific UI features
low_distraction_mode = true        # Minimize visual clutter
focus_mode_highlighting = true     # Highlight active elements
gentle_animations = true           # Use subtle animations
color_coding = true                # Use colors for priority/status

[integrations]
# GitHub integration
github_enabled = false             # Enable GitHub integration
github_sync_issues = true          # Sync GitHub issues as tasks
github_enhance_commits = true      # Add session info to commits
github_update_status = false       # Update GitHub status during sessions

# Slack integration  
slack_enabled = false              # Enable Slack integration
slack_update_status = true         # Update Slack status during sessions
slack_notify_completion = false    # Send completion notifications

# Git integration
git_commit_enhancement = true      # Enhance commit messages with session info
git_auto_commit_on_complete = false # Auto-commit when task completed

# Website blocking
website_blocking = false           # Block distracting websites during sessions
unblock_during_breaks = true       # Allow access during breaks
block_subdomains = true            # Block all subdomains

# Websites to block during sessions
blocked_websites = [
    "facebook.com",
    "twitter.com",
    "reddit.com",
    "youtube.com",
    "instagram.com",
    "tiktok.com",
    "linkedin.com",
    "hacker-news.ycombinator.com"
]

[statistics]
# Data collection
track_detailed_stats = true        # Collect detailed statistics
track_break_usage = true           # Track break patterns
track_productivity_patterns = true # Analyze productivity patterns
track_focus_quality = false        # Self-reported focus quality (experimental)

# Privacy settings
anonymize_task_titles = false      # Hide task titles in exports
export_include_descriptions = true # Include task descriptions in exports

# Retention settings
max_history_days = 365             # Keep statistics for 1 year
auto_archive_old_data = true       # Archive old data automatically

[preferences]
# Startup behavior
auto_start_on_boot = false         # Start pomo-tui on system boot
restore_session_on_startup = true  # Offer to restore interrupted sessions
check_for_updates = true           # Check for updates weekly

# Data management
auto_backup = true                 # Create automatic backups
backup_frequency_days = 7          # Backup every week
max_backup_count = 5               # Keep 5 most recent backups

# Performance settings
enable_query_cache = true          # Cache frequent database queries
cache_duration_minutes = 60        # Cache TTL in minutes
optimize_database_on_startup = false # Run VACUUM/ANALYZE on startup

# Notifications (system-level)
desktop_notifications = true       # Show system notifications
notification_persistence = 5       # Seconds to show notifications

# Keyboard shortcuts (currently fixed, future customization)
vim_mode = false                   # Use vim-style navigation (j/k/h/l)
emacs_mode = false                 # Use emacs-style shortcuts

# Accessibility
high_contrast = false              # Use high contrast colors
large_fonts = false                # Use larger font sizes
screen_reader_support = false      # Enhanced screen reader support
reduce_motion = false              # Reduce animations and transitions

# Advanced settings
debug_mode = false                 # Enable debug logging
log_level = "info"                 # Logging level: error, warn, info, debug, trace
max_log_size_mb = 10               # Maximum log file size
performance_monitoring = false     # Monitor performance metrics

# Database settings
database_path = ""                 # Custom database path (empty = default)
connection_pool_size = 5           # Database connection pool size
query_timeout_seconds = 30         # Database query timeout

# Security settings
encrypt_sensitive_data = false     # Encrypt API tokens and sensitive data
secure_delete = false              # Securely delete sensitive files

# Template configurations for different use cases
[templates.adhd_optimized]
# ADHD-optimized settings
session.duration = 20              # Shorter sessions
session.gentle_transitions = true
session.recovery_prompts = true
audio.ambient_sound = "brown_noise"
audio.ambient_enabled = true
ui.low_distraction_mode = true
ui.gentle_animations = true
statistics.track_focus_quality = true
preferences.desktop_notifications = true

[templates.traditional_pomodoro]
# Traditional Pomodoro Technique settings
session.duration = 25
session.short_break_duration = 5
session.long_break_duration = 15
session.sessions_until_long_break = 4
session.auto_start_breaks = false
session.auto_start_sessions = false
audio.ambient_enabled = false
ui.show_seconds = false

[templates.deep_work]
# Deep work sessions
session.duration = 45              # Longer sessions for deep work
session.short_break_duration = 10
session.long_break_duration = 25
session.sessions_until_long_break = 3
session.auto_start_breaks = true
audio.ambient_sound = "forest"
website_blocking = true
ui.low_distraction_mode = true

[templates.minimal]
# Minimal configuration
audio.sound_enabled = false
ui.compact_mode = true
ui.show_productivity_score = false
ui.show_daily_goal = false
ui.ascii_art_timer = false
statistics.track_detailed_stats = false
integrations.github_enabled = false
integrations.slack_enabled = false

# Sample project-specific configurations
[projects.work]
# Settings when working on work tasks
session.duration = 25
integrations.slack_enabled = true
integrations.website_blocking = true
blocked_websites = [
    "facebook.com",
    "twitter.com",
    "reddit.com",
    "youtube.com"
]

[projects.personal]
# Settings for personal projects
session.duration = 30
audio.ambient_sound = "rain"
integrations.github_enabled = true
website_blocking = false

[projects.study]
# Settings for studying/learning
session.duration = 20              # Shorter for better retention
session.focus_reminders = true
audio.ambient_sound = "library"
ui.show_productivity_score = true
statistics.track_focus_quality = true