# ADHD-Optimized Configuration for pomo-tui
# 
# This configuration is specifically designed for users with ADHD,
# focusing on features that support executive function and sustained attention.
#
# Key principles:
# - Shorter sessions to match ADHD attention spans
# - Gentle transitions and reminders
# - Ambient sound for focus
# - Visual cues and progress tracking
# - Flexible break scheduling
# - Recovery support for interrupted sessions

[session]
# Shorter sessions work better for ADHD brains
duration = 20                      # 20-minute sessions (vs standard 25)
short_break_duration = 5           # Standard short breaks
long_break_duration = 20           # Longer long breaks for recovery
sessions_until_long_break = 3      # More frequent long breaks

# ADHD-friendly automation
auto_start_breaks = true           # Automatic breaks reduce decision fatigue
auto_start_sessions = false        # Manual start maintains intentionality
allow_break_skip = true            # Flexibility when hyperfocused
session_end_sound = true           # Audio cues for time awareness

# ADHD-specific features
gentle_transitions = true          # Gradual timer warnings (5min, 2min, 1min)
recovery_prompts = true            # Help with task resumption
focus_reminders = true             # Gentle reminders every 10 minutes

[audio]
# Audio is crucial for ADHD focus
sound_enabled = true
volume = 0.6                       # Moderate volume to avoid overwhelm

# Brown noise is scientifically shown to help ADHD focus
ambient_enabled = true
ambient_sound = "brown_noise"      # Deep, consistent frequency
ambient_volume = 0.4               # Subtle background presence
fade_in_duration = 5               # Gradual introduction
fade_out_duration = 3              # Smooth transitions

# Gentle notifications to avoid startle response
notification_enabled = true
notification_sound = "soft_bell"   # Non-jarring notification
notification_volume = 0.7
session_start_sound = true
session_end_sound = true
break_start_sound = false          # Avoid over-notification
break_end_sound = true

[ui]
# Visual design for ADHD brains
theme = "dark"                     # Reduced visual stimulation
show_seconds = false               # Less anxiety-inducing
ascii_art_timer = true             # Large, clear visual feedback
progress_bar_style = "blocks"      # Clear progress indication

# Information density
show_session_count = true          # Progress awareness
show_daily_goal = true             # Achievement motivation  
show_productivity_score = true     # Gamification element
show_time_of_day = false          # Avoid time anxiety

# Layout optimized for focus
compact_mode = false               # Spacious layout reduces overwhelm
split_view = true                  # Clear separation of concerns
tab_navigation = true              # Organized navigation

# Realistic but motivating goals
daily_session_goal = 6             # 6 sessions = 2 hours focused work
weekly_session_goal = 30           # Achievable weekly target
goal_reminder = true               # Motivation without pressure

# ADHD-specific visual features
low_distraction_mode = true        # Minimal visual clutter
focus_mode_highlighting = true     # Clear visual hierarchy
gentle_animations = true           # Smooth, calming transitions
color_coding = true                # Visual organization

[integrations]
# GitHub integration for developers with ADHD
github_enabled = false             # Enable if you use GitHub
github_sync_issues = true          # External task integration
github_enhance_commits = true      # Context for future self
github_update_status = false       # Avoid social pressure

# Slack integration
slack_enabled = false              # Enable if needed for work
slack_update_status = true         # Clear boundaries for colleagues
slack_notify_completion = false    # Avoid interrupting flow

# Git workflow support
git_commit_enhancement = true      # Context breadcrumbs
git_auto_commit_on_complete = false # Manual control preferred

# Website blocking is crucial for ADHD
website_blocking = true            # Block distractions
unblock_during_breaks = true       # Allow relaxation during breaks
block_subdomains = true            # Comprehensive blocking

# ADHD-specific blocked sites (high dopamine distractors)
blocked_websites = [
    # Social media (high dopamine)
    "facebook.com",
    "twitter.com", 
    "instagram.com",
    "tiktok.com",
    "snapchat.com",
    
    # Video/entertainment (hyperfocus traps)
    "youtube.com",
    "netflix.com",
    "twitch.tv",
    
    # Information overwhelm
    "reddit.com",
    "hacker-news.ycombinator.com",
    
    # Shopping (impulse control)
    "amazon.com",
    "ebay.com",
    
    # Gaming (time distortion)
    "steam.com",
    "discord.com"
]

[statistics]
# Detailed tracking for pattern awareness
track_detailed_stats = true        # Understand your patterns
track_break_usage = true           # Monitor break effectiveness
track_productivity_patterns = true # Identify peak times
track_focus_quality = true         # Self-awareness tool

# Privacy considerations
anonymize_task_titles = false      # Full context helpful for ADHD
export_include_descriptions = true # Complete information

# Data retention
max_history_days = 365             # Long-term pattern analysis
auto_archive_old_data = true       # Automatic maintenance

[preferences]
# Startup behavior
auto_start_on_boot = false         # Intentional engagement preferred
restore_session_on_startup = true  # Critical for ADHD - avoid lost context
check_for_updates = true           # Stay current with improvements

# Data protection
auto_backup = true                 # Protect against data loss
backup_frequency_days = 3          # Frequent backups
max_backup_count = 10              # Multiple restore points

# Performance for responsiveness
enable_query_cache = true          # Fast response reduces frustration
cache_duration_minutes = 30        # Fresh data while cached
optimize_database_on_startup = false # Avoid startup delays

# System notifications
desktop_notifications = true       # External attention management
notification_persistence = 8       # Longer visibility for processing

# Accessibility and comfort
high_contrast = false              # Standard contrast sufficient
large_fonts = false                # Standard size unless needed
screen_reader_support = false      # Enable if needed
reduce_motion = false              # Gentle animations preferred

# Advanced settings
debug_mode = false                 # Enable if troubleshooting
log_level = "info"                 # Sufficient detail
performance_monitoring = false     # Unless investigating issues

# Security
encrypt_sensitive_data = true      # Protect API tokens
secure_delete = true               # Thorough cleanup

# ADHD-specific reminders and prompts
[adhd_features]
# Custom section for ADHD-specific features
transition_warnings = [5, 2, 1]    # Minutes before session end
focus_check_interval = 10          # Minutes between gentle focus checks
hyperfocus_detection = true        # Detect when user skips multiple breaks
task_switching_delay = 30          # Seconds to prevent impulsive task changes
completion_celebration = true      # Positive reinforcement
daily_reflection_prompt = true     # End-of-day pattern awareness

# Break suggestions based on ADHD needs
[break_suggestions]
short_break_activities = [
    "Stand and stretch for 2 minutes",
    "Take 10 deep breaths",
    "Look out the window",
    "Do light stretching",
    "Hydrate with water",
    "Brief walk around the room"
]

long_break_activities = [
    "Go for a 15-minute walk",
    "Do some physical exercise",
    "Eat a healthy snack",
    "Practice mindfulness/meditation",
    "Listen to music",
    "Connect with nature",
    "Do a creative activity"
]

# Motivational messages for ADHD
[motivation]
session_start_messages = [
    "Let's focus on one thing at a time 🎯",
    "You've got this! Just 20 minutes ⏰",
    "Time to dive into your zone 🌊",
    "Ready to make progress? 🚀"
]

session_complete_messages = [
    "Great job staying focused! 🌟",
    "Another step forward! 💪",
    "You did it! Time for a break 🎉",
    "Focus achieved! You should be proud 👏"
]

productivity_boost_tips = [
    "Try the 2-minute rule: if it takes less than 2 minutes, do it now",
    "Break large tasks into smaller, specific steps",
    "Use body doubling: work alongside others (virtually or in person)",
    "Change your environment when you feel stuck",
    "Celebrate small wins - they add up!",
    "Remember: progress over perfection"
]