# Deep Work Configuration for pomo-tui
#
# This configuration is optimized for deep work sessions as described
# in Cal Newport's "Deep Work: Rules for Focused Success in a Distracted World"
#
# Key principles:
# - Longer, uninterrupted focus sessions (45-90 minutes)
# - Fewer but more substantial breaks
# - Complete distraction elimination
# - Environmental optimization for sustained attention
# - Emphasis on high-value, cognitively demanding work

[session]
# Extended sessions for deep concentration
duration = 45                      # 45-90 minute deep work blocks
short_break_duration = 10          # Longer breaks for recovery
long_break_duration = 30           # Substantial long breaks
sessions_until_long_break = 3      # More frequent substantial breaks

# Automation to maintain flow
auto_start_breaks = true           # Automatic break initiation
auto_start_sessions = false        # Intentional session starts
allow_break_skip = false           # Enforce recovery discipline  
session_end_sound = true           # Clear session boundaries

# Deep work specific features
gentle_transitions = false         # Clean session boundaries
recovery_prompts = true            # Support for complex work resumption
focus_reminders = false            # No interruptions during deep work

[audio]
# Audio environment for sustained focus
sound_enabled = true
volume = 0.5                       # Subtle audio presence

# Ambient sound for concentration
ambient_enabled = true
ambient_sound = "forest"           # Natural sounds for calm focus
ambient_volume = 0.3               # Very subtle background
fade_in_duration = 10              # Gradual environment establishment
fade_out_duration = 5              # Smooth transitions

# Minimal notifications to preserve flow
notification_enabled = true
notification_sound = "gentle"      # Non-disruptive notifications
notification_volume = 0.4
session_start_sound = false        # Silent session entry
session_end_sound = true          # Clear completion signal
break_start_sound = true          # Break initiation
break_end_sound = false           # Gentle return to work

[ui]
# Distraction-free interface
theme = "dark"                     # Reduced visual stimulation
show_seconds = false               # Avoid time anxiety
ascii_art_timer = false            # Minimal timer display
progress_bar_style = "minimal"     # Subtle progress indication

# Essential information only
show_session_count = false         # Avoid performance pressure
show_daily_goal = false            # Focus on quality, not quantity
show_productivity_score = false    # No scoring distractions
show_time_of_day = true           # Awareness of natural rhythms

# Optimized layout for focus
compact_mode = true                # Minimal screen real estate
split_view = false                 # Single point of focus
tab_navigation = false             # Simplified interface

# No daily pressure - focus on quality
daily_session_goal = 0             # Quality over quantity
weekly_session_goal = 0            # No artificial targets
goal_reminder = false              # No goal pressure

# Maximum distraction reduction
low_distraction_mode = true        # Absolute minimal interface
focus_mode_highlighting = false    # No visual distractions
gentle_animations = false          # Static interface
color_coding = false               # Monochrome focus

[integrations]
# GitHub for knowledge workers
github_enabled = false             # Enable if development work
github_sync_issues = false         # Deep work focuses on chosen tasks
github_enhance_commits = true      # Context for future reference
github_update_status = false       # No social signaling

# Communication boundaries
slack_enabled = false              # Enable if absolutely necessary
slack_update_status = true         # Clear unavailability signals
slack_notify_completion = false    # No interruptions

# Version control for knowledge work
git_commit_enhancement = true      # Document thinking process
git_auto_commit_on_complete = false # Manual control preferred

# Essential: complete distraction blocking
website_blocking = true            # Critical for deep work
unblock_during_breaks = false      # Maintain focused environment
block_subdomains = true            # Comprehensive blocking

# Comprehensive distraction blocking for deep work
blocked_websites = [
    # Social media (attention residue sources)
    "facebook.com",
    "twitter.com", 
    "instagram.com",
    "linkedin.com",
    "tiktok.com",
    "snapchat.com",
    
    # News and information (shallow work)
    "reddit.com",
    "hacker-news.ycombinator.com",
    "news.ycombinator.com",
    "medium.com",
    "quora.com",
    "cnn.com",
    "bbc.com",
    "nytimes.com",
    
    # Entertainment (deep procrastination)
    "youtube.com",
    "netflix.com",
    "hulu.com",
    "twitch.tv",
    "spotify.com",
    
    # Shopping (decision fatigue)
    "amazon.com",
    "ebay.com",
    "etsy.com",
    
    # Communication (unless work-critical)
    "gmail.com",
    "outlook.com",
    "slack.com",
    "discord.com",
    
    # General productivity killers
    "imgur.com",
    "pinterest.com",
    "tumblr.com",
    "buzzfeed.com",
    "9gag.com"
]

[statistics]
# Focus on meaningful metrics
track_detailed_stats = true        # Understand deep work patterns
track_break_usage = true           # Monitor recovery effectiveness
track_productivity_patterns = true # Identify peak deep work times
track_focus_quality = false        # Self-assessment can interrupt flow

# Privacy for sensitive work
anonymize_task_titles = true       # Protect intellectual work
export_include_descriptions = false # Minimal data sharing

# Long-term pattern analysis
max_history_days = 365             # Annual pattern analysis
auto_archive_old_data = true       # Automatic maintenance

[preferences]
# Intentional engagement with deep work
auto_start_on_boot = false         # Deliberate deep work initiation
restore_session_on_startup = true  # Continue complex work seamlessly
check_for_updates = false          # No interruptions for updates

# Protect valuable work
auto_backup = true                 # Critical for intellectual output
backup_frequency_days = 1          # Daily backup of valuable work
max_backup_count = 30              # Month of backup history

# Performance for complex work
enable_query_cache = true          # Fast response for large projects
cache_duration_minutes = 120       # Extended cache for session length
optimize_database_on_startup = false # No startup delays

# No external interruptions
desktop_notifications = false      # Complete external silence
notification_persistence = 0       # No persistent distractions

# Comfort for extended sessions
high_contrast = false              # Easy on eyes for long sessions
large_fonts = true                 # Reduce eye strain
screen_reader_support = false      # Enable if needed
reduce_motion = true               # Steady, calm interface

# Minimal system overhead
debug_mode = false
log_level = "error"                # Minimal logging
performance_monitoring = false     # No background monitoring

# Security for intellectual work
encrypt_sensitive_data = true      # Protect valuable intellectual output
secure_delete = true               # Thorough cleanup of sensitive data

# Deep Work specific configuration
[deep_work]
# Session types for different work
session_types = [
    { name = "research", duration = 90, break_duration = 20 },
    { name = "writing", duration = 60, break_duration = 15 },
    { name = "analysis", duration = 45, break_duration = 10 },
    { name = "creative", duration = 30, break_duration = 10 }
]

# Environmental optimization
ideal_conditions = [
    "Quiet, distraction-free environment",
    "Comfortable temperature (68-72°F)",
    "Good lighting (natural preferred)",
    "Hydration available",
    "All materials prepared in advance",
    "Phone in airplane mode or separate room"
]

# Pre-work ritual (5-10 minutes)
preparation_ritual = [
    "Review the specific task/project",
    "Set clear objective for the session", 
    "Gather all necessary materials",
    "Close unnecessary applications/tabs",
    "Clear physical workspace",
    "Set intention for focused work"
]

# Post-work reflection (5 minutes)
completion_ritual = [
    "Document key insights/progress",
    "Note any obstacles encountered",
    "Plan next steps for future sessions",
    "Assess focus quality (1-10)",
    "Record breakthrough moments"
]

# Deep work principles reminders
[principles]
core_concepts = [
    "Deep work produces high value output",
    "Deep work is increasingly rare and valuable",
    "Shallow work should be minimized", 
    "Attention residue reduces cognitive performance",
    "Sustained focus is a skill that requires practice",
    "Quality matters more than time spent"
]

# Strategies for different work types
[work_strategies]
# For writers, researchers, analysts
monastic_approach = {
    description = "Complete isolation from distractions",
    duration = 90,
    breaks = false,
    communication = false
}

# For most knowledge workers
bimodal_approach = {
    description = "Dedicated deep work blocks with shallow work periods",
    deep_blocks = [60, 45, 60],
    shallow_blocks = [30, 15, 30]
}

# For executives, managers
rhythmic_approach = {
    description = "Regular, scheduled deep work sessions",
    daily_session = 45,
    consistent_timing = "9:00-9:45 AM"
}

# For high-demand environments
journalistic_approach = {
    description = "Switch into deep work mode when possible",
    minimum_session = 25,
    maximum_flexibility = true
}