# Minimal Configuration for pomo-tui
#
# This configuration provides the bare minimum functionality
# for users who prefer a simple, no-frills Pomodoro timer.
#
# Features disabled:
# - Audio (silent operation)
# - Statistics tracking
# - Integrations
# - Visual enhancements
# - Automation
# - Advanced UI elements

[session]
# Basic session timing
duration = 25                      # Standard 25-minute sessions
short_break_duration = 5           # 5-minute breaks
long_break_duration = 15           # 15-minute long breaks
sessions_until_long_break = 4      # Every 4 sessions

# Manual control only
auto_start_breaks = false          # Manual break control
auto_start_sessions = false        # Manual session control
allow_break_skip = true            # Flexible break handling
session_end_sound = false          # Silent operation

# No additional features
gentle_transitions = false         # Immediate transitions
recovery_prompts = false           # No session recovery
focus_reminders = false            # No reminders

[audio]
# Complete audio disable
sound_enabled = false              # Silent operation
volume = 0.0
ambient_enabled = false
ambient_sound = "none"
ambient_volume = 0.0
notification_enabled = false
notification_sound = "none"
notification_volume = 0.0
session_start_sound = false
session_end_sound = false
break_start_sound = false
break_end_sound = false

[ui]
# Minimal interface
theme = "dark"                     # Simple dark theme
show_seconds = true                # Show exact time
ascii_art_timer = false            # Simple numeric display
progress_bar_style = "minimal"     # Minimal progress bar

# Essential info only
show_session_count = true          # Basic session counting
show_daily_goal = false            # No goals
show_productivity_score = false    # No scoring
show_time_of_day = false          # No time display

# Compact layout
compact_mode = true                # Space-efficient layout
split_view = false                 # Single view
tab_navigation = false             # Simple navigation

# No goals
daily_session_goal = 0             # No daily targets
weekly_session_goal = 0            # No weekly targets  
goal_reminder = false              # No reminders

# Minimal visual features
low_distraction_mode = true        # Clean interface
focus_mode_highlighting = false    # No highlighting
gentle_animations = false          # No animations
color_coding = false               # No colors

[integrations]
# All integrations disabled
github_enabled = false
github_sync_issues = false
github_enhance_commits = false
github_update_status = false

slack_enabled = false
slack_update_status = false
slack_notify_completion = false

git_commit_enhancement = false
git_auto_commit_on_complete = false

website_blocking = false
unblock_during_breaks = false
block_subdomains = false
blocked_websites = []

[statistics]
# Minimal statistics
track_detailed_stats = false       # No detailed tracking
track_break_usage = false          # No break analysis
track_productivity_patterns = false # No pattern analysis
track_focus_quality = false        # No quality metrics

# No data retention concerns
anonymize_task_titles = false      # No anonymization needed
export_include_descriptions = false # No exports

# Minimal data retention
max_history_days = 30              # 30 days only
auto_archive_old_data = true       # Auto cleanup

[preferences]
# Basic startup
auto_start_on_boot = false         # Manual start
restore_session_on_startup = false # Fresh start always
check_for_updates = false          # No update checks

# No backup needed for minimal use
auto_backup = false                # No automatic backup
backup_frequency_days = 0          # No backups
max_backup_count = 0               # No backup retention

# Minimal performance features
enable_query_cache = false         # No caching
cache_duration_minutes = 0         # No cache
optimize_database_on_startup = false # No optimization

# No notifications
desktop_notifications = false      # No system notifications
notification_persistence = 0       # No persistence

# Standard accessibility
high_contrast = false
large_fonts = false
screen_reader_support = false
reduce_motion = true               # Minimal motion

# Minimal system resources
debug_mode = false
log_level = "error"                # Errors only
performance_monitoring = false     # No monitoring

# No security concerns for minimal use
encrypt_sensitive_data = false     # No sensitive data
secure_delete = false              # Standard deletion

# Minimal feature set
[features]
# Only core timer functionality
enabled_features = [
    "basic_timer",
    "manual_session_control",
    "simple_task_list",
    "basic_break_management"
]

# Everything else disabled
disabled_features = [
    "audio_system",
    "statistics_tracking", 
    "productivity_scoring",
    "goal_management",
    "integration_system",
    "backup_system",
    "notification_system",
    "advanced_ui",
    "automation",
    "pattern_analysis",
    "data_export",
    "session_recovery",
    "focus_assistance"
]

# Minimal help text
[help]
basic_usage = """
Minimal pomo-tui usage:

1. Add tasks: press 'n' to create new task
2. Start session: select task and press 's'  
3. Work: focus for 25 minutes
4. Break: take 5-minute break when timer ends
5. Repeat: continue the cycle

Key shortcuts:
- n: New task
- s: Start session
- p: Pause/resume
- a: Abandon session
- q: Quit

That's it! No bells and whistles, just focused work.
"""

# No advanced features to document
advanced_features = "None available in minimal configuration."